# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f4a3d899eac56be8f780aca0ceec3c05c1a331f076cecb6f587ad5a450eea8c4f60e0bc4d1792c471e91022ded2bb5761489ccf574b588a6322902b5eb05d14

test:
  secret_key_base: 1b55fb3d25b49d37fdb3fb238bd17e4d033c51be9ec73b25cc98340fbe7c52e039001a0131b5b8200b7a88016b45878c8420892d5eb6afeb3e8fe50173c9cd80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
