# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 391b35296210cbb86dbe9f12b35e45bc68209c641690ad61ace4373f95770d7738741d2fbafa36798df186fc01e72ee0413f3f34487bc6ea4e2eace91e4b860e

test:
  secret_key_base: faf3d53fddb55c80ea704a805466619a30aee2920d7b4dc9686dac9428316b1e5975db12d670d3d3db2ea357efbe795285b717842a2cdaa13be588a06a71ebd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
