# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acd645e55d7afa2e69e941abafe418d57ab4e37e2c1a56644dd4cdd871f10187ecdef8bd1e7aa93f9c06bb71c79ae28dcdc9d1a3de4e5ce74fcc212278644a03

test:
  secret_key_base: cfc55ff6c63ae99fab454fd3c6bcbc695832bb855b10396da89359ef9bdff9a92fd0e7080a2167219c61401c17fd13b487d487605e2ee76d7fc7c1da873b4b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
